Movie/Movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static


urlpatterns = [

    path('admin/', admin.site.urls, name="adminpanel"),
    path('', include('recommendation.urls')),
    path('', include('home.urls')),
    path('', include('login_signup.urls')),
    path('', include('movie_admin.urls')),
    path('', include('client.urls')),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)           
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Movie/home/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [

    path('', csrf_exempt(views.home), name="home"), 
    path('genre/<str:movie_genre>', views.home),
    path('toprating/<str:imdb_rating>', views.home),
    path('year/<int:year>', views.home),
    path('recent/<str:latest>', views.home),

]

Movie/movie_admin/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('adminhome/', views.adminhome, name="adminhome"),
    path('adminpanel/', views.adminpanel, name="adminpanel"),
    path('view_rating_details/<int:id>', views.rating_details, name="rating_details"),
    path('delete/<int:id>', views.delete, name="delete"),

    path('list_movies/', views.listMovies, name="list_movies"),
    path('add_movies/', views.addMovies, name="add_movies"),
    path('delete_movies/<int:movie_id>', views.deleteMovies, name="delete_movies"),
    path('edit_movies/<int:movie_id>', views.editMovies, name="edit_movies"),

    path('download_csv/', views.dwonloadCSV, name="download_csv")

]

Movie/movie_admin/models.py
from django.db import models

# Create your models here.

Movie/recommendation/models.py
from django.db import models
from login_signup.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.

class Movie(models.Model):

    GENRE = ( 
        ('Action', 'Action'),
        ('Animation', 'Animation'),
        ('Comedy', 'Comedy'),
        ('Crime', 'Crime'),
        ('Horror', 'Horror'),
        ('Sci-Fi', 'Sci-Fi'),
        ('War', 'War'),
        ('Action Sci-Fi', 'Action Sci-Fi'),
        ('Comedy Crime', 'Comedy Crime'),
        ('Drama Thriller', 'Drama Thriller'),
    )

    YEAR = ( 
        (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'))

    title = models.CharField(max_length=200)
    genre = models.CharField(max_length=100, choices=GENRE)
    poster = models.FileField()
    imdbrating = models.FloatField(default=1.0)
    year = models.IntegerField(null=True, choices=YEAR)

    def __str__(self):
        return self.title


class Client(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE, related_name='client_user')
    movie = models.ForeignKey(Movie, null=True, blank=True, on_delete=models.CASCADE, related_name="client_movie")
    rating = models.FloatField(default=1, validators=[MaxValueValidator(5), MinValueValidator(0)])

    def __str__(self):
        return self.user.username

Movie/login_signup/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm  
from django.contrib.auth.models import User  
from django import forms 
from django.db import transaction
from .models import *


class CreateClientForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {"username": None,
                      "email": None,
                      "password2": None
                      }

    def clean(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')

        if User.objects.filter(username=username).exists():
            raise ValidationError("Username already exists.")

        if User.objects.filter(email=email).exists():
            raise ValidationError("User having this email already exists.")

        return self.cleaned_data


    @transaction.atomic  
    def save(self):
        user = super().save(commit=False) 
        user.is_client = True  
        user.is_admin = False
        user.save()  
        return user



class CreateAdminForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        help_texts = {"username": None,
                      "email": None,
                      "password2": None
                      }

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_admin = True
        user.is_client = False
        user.is_staff = True
        user.save()
        return user



class ImageUploadForm(forms.Form):
    image = forms.ImageField()

Movie/movie_admin/forms.py
from django import forms
from recommendation.models import Movie


class AddMoviesForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'genre', 'poster', 'imdbrating', 'year')

Movie/movie_admin/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from login_signup.decorators import admin_required, client_required
from login_signup.models import User
from recommendation.models import Client, Movie
from .forms import AddMoviesForm
import sweetify
import csv


# Create your views here.

@login_required
@admin_required
def adminhome(request):
    count = Client.objects.filter(user=request.user).count()
    movie_count = Movie.objects.all().count()
    user_count = User.objects.all().count()
    admin_count = User.objects.filter(is_admin=1).count()
    context = {'count': count, 'movie_count': movie_count, 'user_count': user_count, 'admin_count': admin_count}
    return render(request, 'movie_admin/adminhome.html', context)


@login_required
@admin_required
def adminpanel(request):
    users = User.objects.all() 
    clients = Client.objects.all()
    context = {'users': users, 'clients': clients}
    return render(request, 'movie_admin/adminpanel.html', context)


@login_required
@admin_required
def rating_details(request, id): 
    users = User.objects.get(id=id)  
    clients = Client.objects.filter(user=id)  
    counts = Client.objects.filter(user=id).count()
    context = {'clients': clients, 'users': users, 'counts': counts}
    return render(request, 'movie_admin/rating_details.html', context)


@login_required
@admin_required
def delete(request, id): 
    users = User.objects.get(id=id)
    users.delete()
    return redirect('adminpanel')


@login_required
@admin_required
def listMovies(request):
    all_movies = Movie.objects.all()
    context = {'all_movies': all_movies}
    return render(request, 'movie_admin/list_movies.html', context)


@login_required
@admin_required
def addMovies(request):

    if request.method == 'POST':
        print(request)
        form = AddMoviesForm(request.POST, request.FILES)
        print(form)
        if form.is_valid():
            try:
                form.save()
                sweetify.success(request, 'Movie added successfully!',
                                 text='Good job! You have successfully added Movie.',
                                 persistent='ok', icon='success')
            except Exception as e:
                sweetify.error(request, 'Something Went Wrong', text=str(e), persistent='Close', icon='error')
                return redirect('add_movies')

    form = AddMoviesForm()
    return render(request, 'movie_admin/add_movies.html', {'form': form})


@login_required
@admin_required
def deleteMovies(request, movie_id):
    if request.method == 'POST':
        delete_movie = Movie.objects.get(pk=movie_id)
        delete_movie.delete()
        sweetify.success(request, 'Movie deleted successfully!',
                         text='Good job! You have successfully deleted Movie.',
                         persistent='ok', icon='success')
        return redirect('list_movies')


def editMovies(request, movie_id):
    if request.method == 'POST':
        edit_record = Movie.objects.get(pk=movie_id)
        form = AddMoviesForm(request.POST or None, request.FILES or None, instance=edit_record)  
        if form.is_valid:
            edit = form.save(commit=False)
            edit.save()
            sweetify.success(request, 'Movie edited successfully!',
                             text='Good job! You have successfully edited Movie.',
                             persistent='ok', icon='success')

        return redirect('list_movies')
    else:
        edit_record = Movie.objects.get(pk=movie_id)
        form = AddMoviesForm(instance=edit_record)

    return render(request, 'movie_admin/edit_movies.html', {'form': form})



def dwonloadCSV(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="ratings.csv"'
    writer = csv.writer(response)
    writer.writerow(['userId', 'movieId', 'rating'])
    clients = Client.objects.all().values_list('user', 'movie', 'rating')
    for client in clients:
        writer.writerow(client)
    return response

Movie/movie_admin/templates/movie_admin/add_movies.html
{% extends 'movie_admin/admin_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}

    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">
                <div class="page-title">
                    <h1>Dashboard</h1>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{% url 'adminhome' %}">Dashboard</a></li>
                        <li class="active">Add Movie</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>


    <div class="content mt-3">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title mb-3">Add Movie</strong>
                            <span class="float-right">
                                <a href="{% url 'list_movies' %}" class="btn btn-info">List Movies</a>
                            </span>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'add_movies' %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <i class="fa fa-film" aria-hidden="true"></i>
                                    <label for="title">Movie Title:</label><br>
                                    <input type="text" name="title" id="id_title" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <i class="fa fa-list-alt" aria-hidden="true"></i>
                                    <label for="genre">Genre:</label><br>

{#                                    <input type="text" name="genre" id="id_genre" class="form-control" required>#}

{#                                    <select name="genre" id="id_genre" class="form-control" required>#}
{#                                        <option value="Action">Action</option>#}
{#                                        <option value="Animation">Saab</option>#}
{#                                        <option value="mercedes">Mercedes</option>#}
{#                                        <option value="audi">Audi</option>#}
{#                                    </select>#}
                                     {{ form.genre|as_crispy_field  }}


                                </div>
                                <div class="form-group">
                                    <i class="fa fa-star" aria-hidden="true" style="color: gold"></i>

                                    <label for="imdbrating">IMDB Rating:</label><br>
                                    <input type="number" name="imdbrating" id="id_imdbrating" class="form-control"
                                           step="any"
                                           required>
                                </div>
                                <div class="form-group">
                                    <i class="fa fa-calendar" aria-hidden="true"></i>
                                    <label for="year">Year:</label><br>

{#                                    <input type="text" name="year" id="id_year" class="form-control" required>#}
                                     {{ form.year|as_crispy_field  }}
                                </div>


                                <div class="form-group">
                                    <i class="fa fa-picture-o" aria-hidden="true"></i>
                                    <label for="poster">Choose Poster:</label><br>
                                    <input type="file" name="poster" id="id_poster" class="form-control" required>
                                </div>


                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-success">Add</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Movie/movie_admin/templates/movie_admin/admin_base.html
{% load static %}
<!doctype html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Movie Recommendation Admin Dashboard</title>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {#    <link rel="apple-touch-icon" href="{% static 'admin/apple-icon.png' %}">#}
    {#    <link rel="shortcut icon" href="favicon.ico">#}

    <link rel="stylesheet" href="{% static 'admin/vendors/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/themify-icons/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/selectFX/css/cs-skin-elastic.css' %}">


    <link rel="stylesheet" href="{% static 'admin/assets/css/style.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
</head>

<body>


<!-- Left Panel -->

<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">

        <div class="navbar-header">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-menu"
                    aria-controls="main-menu" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="./"><img src="{% static 'admin/images/logo.png' %}" alt="Logo"></a>
            <a class="navbar-brand hidden" href="./"><img src="{% static 'admin/images/logo2.png' %}" alt="Logo"></a>
        </div>

        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'adminhome' %}"> <i class="menu-icon fa fa-dashboard"></i>Dashboard </a>
                </li>
                <h3 class="menu-title">Admin Functionality</h3><!-- /.menu-title -->
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false"> <i class="menu-icon fa fa-user-circle"></i>User</a>
                    <ul class="sub-menu children dropdown-menu">

                        <li><i class="fa fa-table"></i><a href="{% url 'adminpanel' %}">View User's Detail</a></li>
                        <li><i class="fa fa-user-plus"></i><a href="{% url 'adminregister' %}">Add Admin</a></li>

                    </ul>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false"> <i class="menu-icon fa fa-film"></i>Movies</a>
                    <ul class="sub-menu children dropdown-menu">
                        <li><i class="fa fa-table"></i><a href="{% url 'list_movies' %}">List Movies</a></li>

                        <li><i class="fa fa-plus-circle"></i><a href="{% url 'add_movies' %}">Add
                            Movies</a></li>

                    </ul>
                </li>


                <h3 class="menu-title">Home</h3><!-- /.menu-title -->
                <li class="menu-item">
                    <a href="{% url 'home' %}"> <i class="menu-icon fa fa-home"></i>Home</a>

                </li>


            </ul>

        </div><!-- /.navbar-collapse -->
    </nav>
</aside><!-- /#left-panel -->

<!-- Left Panel -->

<!-- Right Panel -->

<div id="right-panel" class="right-panel">

    <!-- Header-->
    <header id="header" class="header">

        <div class="header-menu">

            <div class="col-sm-7">
                <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                <div class="header-left">
                    <button class="search-trigger"><i class="fa fa-search"></i></button>
                    <div class="form-inline">
                        <form class="search-form">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search ..."
                                   aria-label="Search">
                            <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-sm-5">
                <div class="user-area dropdown float-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
                       aria-expanded="false">
                        <img class="user-avatar rounded-circle" src="{{ user.image.url }}"
                             alt="User Avatar" width="50" height="30">
                    </a>

                    <div class="user-menu dropdown-menu">
                        <a class="nav-link" href="{% url 'home' %}"><i class="fa fa-home"></i> Home</a>

                        <a class="nav-link" href="{% url 'adminhome' %}"><i class="fa fa-user"></i> Profile</a>
                        <hr>


                        <form class="navbar-form navbar-right" action="{% url 'logoutall' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <li>
                            <span class="glyphicon glyphicon-log-out" style="margin-top: 10px;">
                            </span>

                                    <input type="submit" value="logout" class="btn btn-danger">

                                </li>
                            </div>

                        </form>
                    </div>
                </div>


            </div>
        </div>

    </header><!-- /header -->
    <!-- Header-->
    {% block body %}
    {% endblock %}

</div><!-- /#right-panel -->

<!-- Right Panel -->
{% load sweetify %}

{% sweetify %}

<script src="{% static 'admin/vendors/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'admin/vendors/popper.js/dist/umd/popper.min.js' %}"></script>
<script src="{% static 'admin/vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'admin/assets/js/main.js' %}"></script>


<script src="{% static 'admin/assets/js/dashboard.js' %}"></script>
<script src="{% static 'admin/assets/js/widgets.js' %}"></script>

<!-- Datatables-->
<script src="{% static 'admin/vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'admin/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'admin/vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'admin/vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'admin/vendors/jszip/dist/jszip.min.js' %}"></script>
<script src="{% static 'admin/vendors/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'admin/vendors/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'admin/vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'admin/vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'admin/vendors/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static 'admin/assets/js/init-scripts/data-table/datatables-init.js' %}"></script>
</body>

</html>

Movie/movie_admin/templates/movie_admin/adminhome.html
{% extends 'movie_admin/admin_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}

    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">
                <div class="page-title">
                    <h1>Dashboard</h1>
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li class="active">Dashboard</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content mt-3">

        <div class="col-sm-12">
            <div class="alert  alert-success alert-dismissible fade show" role="alert">
                <span class="badge badge-pill badge-success">Welcome!</span> to our admin dashboard.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>


        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-flat-color-1">
                <div class="card-body pb-0">
                    <div class="dropdown float-right">
                        <button class="btn bg-transparent dropdown-toggle theme-toggle text-light" type="button"
                                id="dropdownMenuButton1" data-toggle="dropdown">
                            <i class="fa fa-cog"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                            <div class="dropdown-menu-content">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </div>
                    </div>
                    <h4 class="mb-0">
                        <span class="count">{{ movie_count }}</span>
                    </h4>
                    <p class="text-light"><i class="fa fa-film"></i> Total Movies</p>

                    <div class="chart-wrapper px-0" style="height:70px;" height="70">
                        <canvas id="widgetChart1"></canvas>
                    </div>

                </div>

            </div>
        </div>
        <!--/.col-->

        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-flat-color-2">
                <div class="card-body pb-0">
                    <div class="dropdown float-right">
                        <button class="btn bg-transparent dropdown-toggle theme-toggle text-light" type="button"
                                id="dropdownMenuButton2" data-toggle="dropdown">
                            <i class="fa fa-cog"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                            <div class="dropdown-menu-content">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </div>
                    </div>
                    <h4 class="mb-0">
                        <span class="count">{{ user_count }}</span>
                    </h4>
                    <p class="text-light"><i class="fa fa-user-circle"></i> User's Count</p>

                    <div class="chart-wrapper px-0" style="height:70px;" height="70">
                        <canvas id="widgetChart2"></canvas>
                    </div>

                </div>
            </div>
        </div>
        <!--/.col-->

        <div class="col-sm-6 col-lg-3">
            <div class="card text-white bg-flat-color-3">
                <div class="card-body pb-0">
                    <div class="dropdown float-right">
                        <button class="btn bg-transparent dropdown-toggle theme-toggle text-light" type="button"
                                id="dropdownMenuButton3" data-toggle="dropdown">
                            <i class="fa fa-cog"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton3">
                            <div class="dropdown-menu-content">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </div>
                    </div>
                    <h4 class="mb-0">
                        <span class="count">{{ admin_count }}</span>
                    </h4>
                    <p class="text-light"><i class="fa fa-user-md"></i> Admin's Count</p>

                </div>

                <div class="chart-wrapper px-0" style="height:70px;" height="70">
                    <canvas id="widgetChart3"></canvas>
                </div>
            </div>
        </div>
        <!--/.col-->


        <div class="col-sm-6 col-lg-2 offset-1">

            <a href="{% url 'download_csv' %}" id="download_csv">
            <button class="btn " style="background-color: #272c33; color: white"><i class="fa fa-download"></i> Export Rating CSV</button>
            </a>

        </div>
        <!--/.col-->


        <!--/.col-->
    </div> <!-- .content -->

    <!-- User Profile Card -->
    <div class="content mt-3">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title mb-3">Profile Detail</strong>
                        </div>
                        <div class="card-body">
                            <div class="mx-auto d-block">
                                <img class="rounded-circle mx-auto d-block" src="{{ user.image.url }}" width="150;"
                                     height="150;"
                                     style="margin-top: 50px; border: 2px solid black; padding: 10px;"
                                     alt="Card image cap">

                                <h5 class="text-sm-center mt-2 mb-1">{{ request.user }}</h5>
                                <form action="{% url 'upload_pic' %}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="text-sm-center mt-2 mb-1" style="margin-left: 18%">
                                        <input id="id_image" type="file" name="image">

                                    </div>
                                    <div class="text-sm-center mt-2 mb-1">
                                        <input type="submit" value="Submit" class="btn btn-success">
                                    </div>
                                </form>

                            </div>

                            <table class="table table-hover mt-4 text-center">
                                <tbody>
                                <tr>
                                    <td>Username:</td>
                                    <td>{{ request.user }}</td>
                                </tr>
                                <tr>
                                    <td>Email:</td>
                                    <td>{{ request.user.email }}</td>
                                </tr>
                                <tr>
                                    {% if request.user.is_client %}
                                        <td> User Type:</td>
                                        <td> User</td>
                                    {% else %}
                                        <td> User Type:</td>
                                        <td> Admin</td>
                                    {% endif %}
                                </tr>

                                <tr>
                                    <td>User ID :</td>
                                    <td>{{ request.user.id }}</td>
                                </tr>
                                <tr>
                                    <td>Joined Date:</td>
                                    <td>{{ request.user.date_joined }}</td>
                                </tr>

                                <tr>
                                    <td>Last Seen:</td>
                                    <td>{{ request.user.last_login }}</td>
                                </tr>

                                <tr>
                                    <td>Movie Rated:</td>
                                    <td>{{ count }}</td>
                                </tr>


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}